version: "3.8"

services:
  database:
    image: mysql:5.7
    container_name: db_mysql57
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "23306:3306"

  php-apache:
    container_name: app
    build:
      context: ./php
    ports:
      - "8081:80"
    volumes:
      - ./www:/var/www/
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - database

volumes:
  #- db_data:/var/lib/mysql
  db_data:
